create table cars (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    make VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year INT NOT NULL CHECK(year > 1960),
    city VARCHAR(50) NOT NULL,
    color VARCHAR(50),
    vin VARCHAR(50) NOT NULL,
    broken BOOLEAN DEFAULT FALSE
);

insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Lancer Evolution', 2006, 'Shangtuhai', 'Goldenrod', 'WAUXU64BX2N227328', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lincoln', 'Town Car', 1988, 'Lauro de Freitas', 'Khaki', 'JM1NC2EF9A0591016', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'FX', 2006, 'Ponte Nova', 'Yellow', 'SAJWA4FBXDL028501', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Daytona', 1984, 'São Pedro', null, '1G6D25EY7B0412378', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', '7 Series', 2012, 'Belovodskoye', 'Mauv', 'SCFBF04BX8G217658', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Insight', 2002, 'Yuanping', 'Maroon', 'WAUDV94F57N535356', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chrysler', 'Sebring', 1999, 'Quipot', 'Mauv', 'TRUSC28N841235411', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Impreza', 2008, 'Cabo', 'Indigo', '1GKS1GEJ4DR538030', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Cabriolet', 1996, 'Oja', 'Turquoise', '19UUA9F26EA838287', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Insight', 2011, 'Xiamao', 'Khaki', '5LMCJ1A9XFU646993', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'DeVille', 1992, 'Mateur', 'Aquamarine', '1B3CB9HA7AD600194', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Civic', 1994, 'Albania', 'Violet', '1GYUCHEF8AR644826', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hummer', 'H1', 2001, 'Ambatondrazaka', 'Indigo', 'WAUDGAFL4EA206103', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Suburban 2500', 1997, 'Желино', 'Aquamarine', '1G6AA5RA0E0764838', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'G', 1995, 'Billings', 'Aquamarine', 'WAUMK98KX9N556187', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Land Cruiser', 2004, 'Tsybulevka', 'Red', '19XFB4F2XEE180073', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Park Avenue', 1994, 'Toyonaka', 'Indigo', 'JH4CU4F49BC121869', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'M Roadster', 2007, 'Gadingrejo', 'Crimson', '5N1AR1NB8BC344859', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Astro', 1995, 'Shiquanhe', 'Fuscia', 'WAUFFBFL9BA635878', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Discovery', 1994, 'Il’ya', 'Puce', '3D7JB1EK7BG029921', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', '525', 2001, 'Gustavsberg', null, '1GYS4KEF3BR754332', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Legacy', 1993, 'Köping', 'Khaki', 'SALAG2V60FA979698', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Rolls-Royce', 'Phantom', 2010, 'Áyioi Apóstoloi', 'Maroon', 'WAUSF98K29A624002', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Compass', 2011, 'Wangyi Zhendian', null, '1D7RE3GKXBS937405', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Passport', 1994, 'Malabor', 'Aquamarine', 'WBALZ5C5XCC773677', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Esteem', 1999, 'Quinta da Queimada', 'Orange', 'WAULC68E04A865801', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'SC', 2006, 'San Salvador', 'Pink', '1FTWF3C59AE776534', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'V50', 2005, 'Paico', 'Aquamarine', 'SCBGR3ZA2DC808410', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lincoln', 'Blackwood', 2003, 'Don Carlos', 'Teal', 'WAUFL54D31N834387', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lotus', 'Esprit', 1993, 'Khóra', 'Mauv', 'SCBZK25E83C040852', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'GTI', 1990, 'Jiangyan', 'Turquoise', '5FRYD4H46FB896934', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram 1500', 1998, 'Haz-Zebbug', 'Blue', 'WBA4C9C56FD201503', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'Integra', 1997, 'Burgkirchen', null, 'WVWBB7AJ0DW519751', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', '240SX', 1997, 'Nakkila', null, 'JHMZE2H52ES525933', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Kia', 'Sorento', 2008, 'Chicacao', 'Red', '1FTSW2A5XAE240770', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'Coupe GT', 1985, 'Tongle', 'Yellow', 'WAUGU54D21N875594', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'A3', 2010, 'Usicayos', 'Violet', '2G4GU5GV8C9444377', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Pathfinder', 2009, 'Batangtoru', 'Mauv', '1G6AZ5S33F0827050', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Escort', 1999, 'Qo‘qon', null, '1C3ADEAZ6DV398136', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chrysler', 'Town & Country', 2011, 'Zhongzuiling', 'Green', 'WAU3FAFR6BA166802', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Range Rover Sport', 2007, 'Mat-i', 'Red', 'WA1VMAFE5BD521692', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F250', 2002, 'Kalisangkrah Lor', 'Goldenrod', '1FTSX2A5XAE303699', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Truck Xtracab SR5', 1989, 'Elekmonar', 'Yellow', 'WBAYF8C53FD336733', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Esteem', 1995, 'Petite Anse', 'Orange', '1FMJU1J55AE234267', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Tempo', 1994, 'Cete', null, 'JTDKN3DP4E3931030', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F-Series Super Duty', 2010, 'Haifa', 'Blue', '5LMJJ3H58CE054990', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Outback', 2006, 'Presidente Epitácio', null, '1G6DA67V480981919', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Endeavor', 2011, 'Kotakaya Dua', 'Maroon', 'SCFFDCBD8CG120402', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lincoln', 'Mark VIII', 1998, 'Had Kourt', 'Puce', 'WBAEB53568C261399', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Explorer', 2012, 'Íquira', 'Crimson', 'WAUAH68DX1A355306', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', '6000', 1985, 'Noramarg', null, 'WDDGF4HB7ER964565', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maybach', '62', 2012, 'Drammen', null, '1GYS3AEF1DR916054', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'E-350 Super Duty Van', 2006, 'Tsyelyakhany', 'Purple', 'WBAWV5C50AP207669', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Montero', 1996, 'São Gotardo', 'Crimson', '1FTEW1CM1EF617109', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'B-Series Plus', 1993, 'Niaohe', null, '3C63DRAL9CG030376', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Scion', 'xD', 2008, 'Rote', 'Yellow', '4T1BF3EK2BU076474', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lotus', 'Esprit', 1995, 'Dorchester', 'Khaki', 'WAUAF98E76A852188', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'M3', 2005, 'Bissen', 'Indigo', '1N6AD0CU0FN359543', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Sable', 1999, 'Imari', 'Khaki', 'WAU2GAFC0DN680323', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'GS', 1995, 'Lafayette', 'Turquoise', '1N6AD0CUXCC554170', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Silverado 2500', 2006, 'Qingxi', 'Red', '1D7CE3GK0AS268839', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'STS', 2005, 'Danauparis', 'Khaki', 'WAUDF48H18K404634', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lamborghini', 'Diablo', 1995, 'Camachile', 'Mauv', 'WBSWD93588P217477', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Bonneville', 2003, 'Vitim', 'Green', 'WBA1J7C51FV757712', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Jetta', 1999, 'Cevicos', 'Goldenrod', '1GD021EG5FZ307346', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'GTO', 1965, 'Gitega', null, 'WA1AY74L77D721486', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'SLK-Class', 2004, 'Loučovice', 'Teal', '1N6AA0CA4DN696597', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maserati', '228', 1990, 'Hyesan-dong', 'Red', 'WAUDH74F87N627671', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Legacy', 2009, 'Quebrada Larga', 'Green', '3VW467ATXDM494028', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F150', 2002, 'Darwin', 'Fuscia', 'WA1TFAFL0EA615274', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Pajero', 1992, 'Gemblengmulyo', 'Pink', '19UUA65595A646551', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'HS', 2010, 'Mendeleyevo', 'Indigo', 'WVWAN7AN6DE667771', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Isuzu', 'Trooper', 1992, 'Omaha', 'Yellow', 'WBAXH5C57DD183744', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Sierra', 2010, 'Brandýs nad Labem-Stará Boleslav', 'Turquoise', 'SCFBB03B08G424380', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Avenger', 2012, 'Paris 09', 'Violet', 'WA1LYAFE7AD510512', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Econoline E350', 1995, 'Loma Bonita', 'Maroon', '3N1AB7AP7FY251456', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Econoline E350', 1998, 'Pavlovskaya', 'Orange', '1G6KD57Y07U467320', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'MDX', 2002, 'Musalerr', 'Yellow', 'WAUAFAFL9FA618086', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'B9 Tribeca', 2007, 'Saldanha', 'Mauv', 'WAUJFAFH9BN847155', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Explorer', 2006, 'Hövsan', 'Yellow', 'WBAFU9C5XDD434240', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Daewoo Lacetti', 2006, 'Novi Itebej', 'Purple', '1FTWW3B56AE329242', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Kia', 'Sephia', 1997, 'Guanjiabao', 'Violet', 'JTDZN3EU2E3224026', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Savana 1500', 1997, 'Boa Esperança', 'Maroon', 'WAULL44E75N783682', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', '370Z', 2011, 'Shakhun’ya', 'Khaki', '4JGBB2FB6AA652040', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Eclipse', 2004, 'Faqīrwāli', 'Crimson', '2HNYD18685H142308', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Outlander', 2012, 'Banī Khallād', 'Turquoise', 'WAUWFAFR6EA653709', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'C70', 2004, 'Gabú', 'Indigo', 'JN1CV6EK0DM899875', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Isuzu', 'Amigo', 2000, 'Poitiers', 'Goldenrod', '3C4PDDDG3DT179581', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Ranger', 2003, 'Bum Bum', 'Puce', '1GYFK36239R830330', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Firebird', 1991, 'Korenëvo', 'Puce', '1G6KD5EY5AU151308', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram 1500 Club', 1997, 'Rokytnice nad Jizerou', 'Crimson', '5TDBM5G11CS623315', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Miata MX-5', 1994, 'Montecillo', 'Yellow', '1FMJK1K56AE927935', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'SJ', 1991, 'Rajal Norte', 'Green', '19UUA66267A646658', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Renault', 'Alliance', 1983, 'Arteche', 'Violet', 'WBSBL93464J374348', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Swift', 2005, 'Cawalo', 'Violet', 'JTHBE1BL4FA153229', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Sidekick', 1997, 'Lima', 'Green', 'WAUKH98E87A403473', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Miata MX-5', 2003, 'Guandi', 'Khaki', '5FNRL5H21EB098532', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Escort', 1993, 'Kazaure', 'Blue', '1N4AL2APXBC420777', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'M', 2006, 'Chengdong', 'Green', '2B3CK5CT5AH271547', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Accord', 2011, 'Évreux', 'Purple', '2G4GN5EKXC9672595', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Hearse', 1996, 'Ucluelet', null, 'WAUNF98PX8A842115', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Avalon', 2004, 'Bulgan', 'Puce', 'JTJBM7FX3B5143845', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Corvette', 2006, 'Arāk', 'Green', 'KMHHT6KD2DU674254', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Plymouth', 'Grand Voyager', 1995, 'São Luís do Quitunde', 'Red', '5N1AN0NW5EN422368', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Passat', 1998, 'Banjar Sandinggianyar', 'Maroon', '3VW517AT4EM897264', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'XLR', 2006, 'Ust’-Kut', 'Crimson', 'SALVP2BG4FH074595', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Eagle', 'Talon', 1997, 'Martapura', 'Violet', 'WBAVM1C58EV789979', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Cherokee', 1995, 'Abilay', 'Purple', '19VDE1F33EE766063', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Grand Cherokee', 2004, 'Hepu', 'Aquamarine', 'WBXPA93446W473942', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Savana', 2009, 'Qiankeng', 'Purple', 'WBSBR93456P627304', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Legacy', 1989, 'Kokaj', 'Pink', '5TDDK3DC4DS380271', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram 2500', 2005, 'Vichuga', 'Yellow', '4JGDA2EB7DA717835', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Impreza', 1996, 'Montargis', 'Teal', 'WBA3R5C53FK897848', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'S60', 2007, 'São Sebastião', 'Indigo', '4T1BF1FK9DU754370', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Avalon', 2006, 'Jelbuk', 'Mauv', '1YVHZ8BH6C5985755', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Grand Cherokee', 2008, 'San Isidro', 'Indigo', '3D7TP2CT1AG639744', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Austin', 'Mini', 1963, 'Bazhu', 'Purple', 'WBA3G7C53EK471903', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Eclipse', 2005, 'El Hamma', 'Fuscia', 'JTHKD5BH9C2942715', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'Alpina B7', 2008, 'Yingtou', 'Aquamarine', '1GYS3HEF0ER282309', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Ranger', 2006, 'Regueiro', 'Goldenrod', '1GD11ZCG1BF783470', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Accord', 1995, 'Kiili', 'Indigo', '1G6AB5R34D0862185', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Isuzu', 'Rodeo Sport', 2002, 'Kota Kinabalu', 'Puce', '3GYT4NEF1CG804412', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'DeVille', 2002, 'Jujur', 'Crimson', 'WDCYC3HF9EX382848', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'A8', 2001, 'Hongmei', 'Red', 'JM1DE1KY2D0621080', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Saturn', 'Relay', 2006, 'Bucu Kidul', 'Goldenrod', '2T3BF4DV1CW373083', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Quest', 2007, 'Borlänge', 'Green', '5LMJJ3H55BE407037', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Caravan', 2000, 'Santuario', 'Khaki', 'WBAUT9C52CA582117', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Saab', '9000', 1994, 'Fenglin', 'Mauv', 'WA1DGBFP1DA119585', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Suburban 1500', 1992, 'Plavy', 'Crimson', '1FTKR1AD7BP690018', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Porsche', 'Cayenne', 2008, 'Bylym', null, 'YV4902DZ6B2465074', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Matrix', 2005, 'Santa Rosa de Cabal', 'Indigo', 'KL4CJGSB5EB264371', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Eagle', 'Talon', 1997, 'Ganlin', 'Yellow', '1G4HR57Y68U904744', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Land Cruiser', 2001, 'Bandhagen', 'Mauv', '1NXBU4EE9AZ341489', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Grand Cherokee', 2002, 'Pacajus', 'Turquoise', '1G6DV57V490623199', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Swift', 1990, 'Imperatriz', 'Teal', 'JTHBK1GG9F2082608', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maserati', 'Quattroporte', 2009, 'Rambouillet', 'Aquamarine', 'WVWAP7AN5DE033037', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ferrari', 'FF', 2012, 'Stanisław Dolny', 'Aquamarine', 'SCFFDAAMXDG596657', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Impala', 2010, 'Bangkok', 'Violet', '3VW467AT1DM592428', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'A4', 2010, 'Palencia', 'Indigo', '1D7RV1CT0BS343800', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 1500', 1998, 'Catarman', 'Teal', '3VWKX7AJ8DM719730', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Corvette', 2011, 'Deauville', 'Fuscia', 'KNAGM4AD1B5389911', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Miata MX-5', 1999, 'Tegalloa', 'Blue', 'WBAVM5C50FV090838', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Avenger', 1995, 'Liborina', 'Green', '4T1BK3DB2BU269298', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Excel', 1994, 'Prado', 'Khaki', 'SAJWA1CB0CL296278', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Crown Victoria', 2005, 'Aguada de Pasajeros', 'Red', '2T1KE4EE8DC162251', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Tracer', 1994, 'Umabay', 'Purple', '3VW1K7AJ2EM504128', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'D250', 1993, 'Kyŏngsŏng', 'Khaki', 'JTDKN3DU3A0784989', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'ES', 1991, 'Hulutao', 'Violet', 'WBAPN7C58AA957775', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maybach', '62', 2011, 'Taytayan', 'Red', 'WP0CA2A89BU497412', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'M-Class', 2007, 'Chayuan', 'Khaki', '1G4GF5G38CF283836', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Suburban 1500', 1999, 'Fujishiro', 'Maroon', '5FRYD3H63GB248433', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Kia', 'Sephia', 1996, 'Vila Viçosa', 'Puce', '1G6DK5E31C0818615', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 2500', 2006, 'Sambong', 'Teal', 'WAUBVAFB7BN355646', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'S-Class', 1990, 'Qingxi', 'Violet', '5TDDK3DC8DS685028', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Bonneville', 1990, 'Miaoquan', 'Teal', 'KMHCT4AE1FU416559', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Miata MX-5', 2007, 'Lukrejo', 'Maroon', 'JTDKN3DUXA0535735', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'M', 2009, 'Jiulong', 'Indigo', 'WAUJF98KX9N428815', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Prix', 1990, 'Poroj', 'Aquamarine', 'KNADH4A33B6010772', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Elantra', 2010, 'Spodnja Hajdina', 'Blue', 'SALAB2D46AA026128', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Alfa Romeo', 'Spider', 1994, 'Huancapi', null, '1B3CB7HB0AD570212', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Enclave', 2008, 'Francisco I Madero', 'Khaki', '1VWAH7A36EC017225', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Aveo', 2008, 'Dongcun', 'Yellow', '19XFA1E30AE205519', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Isuzu', 'Space', 1992, 'Santo Tomás', 'Purple', '5YMGY0C53AL424925', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'XC60', 2012, 'Rääkkylä', 'Maroon', '3D73M4HL1AG033132', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Highlander', 2009, 'U Minh', 'Yellow', '1G6AC5S33E0791425', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Corvette', 1966, 'Angra dos Reis', 'Violet', 'WBAYF8C54FD001027', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Geo', 'Metro', 1993, 'Houston', 'Teal', 'WA1LMBFE4FD623911', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 3500', 2002, 'Ciriri', 'Goldenrod', 'WBALL5C58CE479166', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'ES', 2001, 'Xufeng', 'Orange', 'WA1LMBFE5FD603487', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Cabriolet', 1997, 'Bumba', 'Teal', '1G6AE1RX2F0837016', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'V8', 1991, 'Songshu', 'Mauv', 'WA1AY74L88D554542', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maybach', '62', 2003, 'Jizhou', 'Green', 'JN8AZ2KR2ET966345', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Avenger', 1995, 'Phra Pradaeng', 'Blue', 'SCFEDCAD6CG875612', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Quest', 1993, 'Mashizhai', 'Purple', '2T1BPRHE2EC224845', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Odyssey', 2003, 'Plavy', 'Crimson', 'W04G05GV4B1868121', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Suburban 1500', 2008, 'Changma', null, 'WAUSH78E88A577498', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'E150', 2008, 'Puerto Aisén', 'Blue', 'YV1902FH2D2492485', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Hummer', 'H1', 1995, 'Chengxiang', 'Khaki', 'KNAGM4AD5C5780450', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'G-Series 1500', 1997, 'Caridade', 'Pink', '1G6KF57993U385437', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Discovery', 2000, 'Cisagu', null, 'WAUBF98E28A908593', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Sentra', 2009, 'Jambulang', 'Fuscia', 'WAUDFAFL9AA711647', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'Seville', 2000, 'Eira Nova', 'Green', '1G6DF8E57D0809748', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'S-Class', 1991, 'Labog', 'Pink', '1G6KF54945U221911', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Isuzu', 'Rodeo', 1993, 'Hatton', 'Puce', '2HNYD2H29AH139527', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lincoln', 'Continental Mark VII', 1990, 'Yandun', null, 'WAUVT58E84A144306', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Land Cruiser', 2002, 'Yambio', 'Indigo', 'WA1AV94L79D354886', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Prix', 1962, 'Kakegawa', null, 'WAUUL68E65A638585', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Firebird', 1997, 'Seixas do Douro', null, 'WBAVA37567N979815', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'Q5', 2012, 'Uglovoye', 'Khaki', 'WBAUC7C5XAV506171', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Insight', 2001, 'Louredo', 'Orange', 'WBA4B3C56FD342667', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Am', 1989, 'Yuanling', 'Green', 'WAUNF78P58A405269', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Swift', 2001, 'Santiago', 'Pink', 'WBAET37482N689103', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Mazdaspeed 3', 2008, 'Yaxi', 'Mauv', '3VW1K7AJ0CM247418', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hummer', 'H2', 2009, 'Naran-mandokhu Somon', 'Pink', '1D4PT2GK3BW829494', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'ZDX', 2011, 'Payapa', null, '3D73M4HL0BG500428', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Smart', 'Fortwo', 2012, 'Masākin', 'Teal', 'JN1AZ4EH5FM005036', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Plymouth', 'Neon', 1996, 'Haarlem', 'Fuscia', '5FRYD3H43FB112137', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 2500', 2000, 'Leshukonskoye', 'Blue', 'WAUJC68E05A302837', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Silverado', 2009, 'Pishaj', 'Yellow', '1GYS4LKJ9FR372178', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Tempo', 1991, 'Anār Darah', 'Mauv', 'KNADM5A30D6207967', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Millenia', 2001, 'Stockholm', 'Pink', '5TDBK3EH1CS308962', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Savana 1500', 2002, 'Chrysó', 'Teal', 'WA1DGBFP9DA410920', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Lancer Evolution', 2006, 'Heiiyugou', 'Violet', '4T1BF1FK6CU729991', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Sequoia', 2002, 'Farsta', null, 'WBAYE4C55DD144724', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'GL-Class', 2007, 'Ust’-Donetskiy', 'Turquoise', '1D7RV1CPXAS583437', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Plymouth', 'Voyager', 1995, 'West Hartford', 'Puce', 'WA1C8BFP3FA336244', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', '240SX', 1993, 'Luchegorsk', 'Aquamarine', '1G6DC67A990770496', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'LeSabre', 2003, 'Itaberaí', 'Puce', 'WAUJC68E12A545133', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Elantra', 2004, 'Bayan Ewenke Minzu', 'Pink', '1GKUCEEF1AR166032', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Tercel', 1992, 'Avignon', 'Teal', '1G6DP1ED7B0254437', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Saturn', 'Ion', 2004, 'Carvoeira', null, '5UXZV8C59BL789988', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', 'Intrigue', 1999, 'Zliv', 'Crimson', '1G6DA67V480023024', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Ranger', 2000, 'Klatovy', 'Red', 'YV4902NB3F1865283', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'SL-Class', 2000, 'Jaguariaíva', 'Mauv', 'WBA3B1G54EN073247', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Tahoe', 2008, 'Jaga', null, '1GYS3HEF7BR401341', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Tempest', 1965, 'Byuravan', 'Crimson', 'WAUBFAFL9AA343090', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'rio', 1998, 'Yurimaguas', 'Turquoise', 'JN1AZ4EH6EM138371', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Equinox', 2005, 'Karangkedawung', 'Crimson', '1FMJK1H57DE688097', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', '323', 1995, 'Quận Phú Nhuận', 'Aquamarine', 'WBASP0C54DC948298', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Grand Marquis', 2002, 'Meukek', 'Khaki', 'WBAGL83585D420064', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Xtra', 1995, 'Comagascas', 'Yellow', '3D73Y4EL4AG099957', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Porsche', 'Boxster', 1998, 'Cihurip Satu', 'Yellow', 'WBAFR9C53BC033939', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'QX', 2000, 'Abut', 'Fuscia', '1N6AF0KY3FN699252', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Forester', 2002, 'Miami', 'Fuscia', 'WBSBR93433P925300', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'APV', 1992, 'Nachalovo', 'Green', '3D7JB1ET6BG417554', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Truck', 1995, 'Hita', 'Green', '1G4HK5E95AU753062', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Montero Sport', 2004, 'Ādīs Zemen', 'Violet', 'WAUJC68E02A574395', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Savana 1500', 2005, 'Babahoyo', 'Crimson', 'JH4CW2H62CC606269', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'G', 2002, 'Sinargalih', 'Crimson', '5XYKT3A19BG447724', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', '240SX', 1996, 'Manikchari', 'Khaki', '1G6AB5RA2E0524932', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Plymouth', 'Grand Voyager', 1992, 'Obrera', null, '1GYFC262X9R862019', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Probe', 1992, 'Qarah Bāgh', 'Khaki', '1FMJU1H58AE486472', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Edge', 2007, 'Zaporizhzhya', null, '1G6AE1RX9F0975538', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Cougar', 1968, 'Mirpur Khas', 'Khaki', 'JH4NA12613T461512', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Venture', 2005, 'Strážnice', 'Crimson', '1ZVBP8JS7B5652717', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Suzuki', 'Aerio', 2005, 'Calape', 'Maroon', 'YV4940BL1D1070123', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'CR-Z', 2012, 'Konin', 'Puce', '1D4PT5GK6BW714101', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Suburban 2500', 1992, 'Huangzhu', 'Puce', 'SCBFT7ZAXEC130351', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'RDX', 2012, 'Arroio do Meio', 'Indigo', '1G6DV1EPXD0240616', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Regal', 1991, 'Balas', null, '2G4GU5GX2E9164376', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'MPV', 2001, 'Guangping', 'Puce', '1FTSW3A57AE687689', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Daytona', 1992, 'Nunmanu', 'Turquoise', 'JN1CV6EKXFM348839', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Smart', 'Fortwo', 2010, 'Kristiansand S', 'Violet', 'SCBGH3ZA1FC559572', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'MX-5', 2008, 'Hamburg', null, 'WDDLJ7GB6FA647554', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'D250', 1993, 'Waina', 'Blue', 'WBSBR93464P783476', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'SRX', 2011, 'Yangjiao', 'Turquoise', '1FMJU1F59AE433556', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'M', 2012, 'Khlong Luang', 'Blue', '1G6AL5SX5D0132442', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Porsche', 'Cayman', 2006, 'Santa Cruz del Norte', 'Khaki', '5XYKT3A16BG325127', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'A4', 2009, 'Orenburg', 'Khaki', 'WAUAF78E66A570497', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chrysler', 'Prowler', 2002, 'Ōyama', 'Puce', 'WBAEW534X4P706404', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Impreza', 1998, 'Changning', 'Yellow', '3C3CFFJH6ET853116', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Park Avenue', 1993, 'Novosin’kovo', null, '4USBT53564L606292', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'Q', 1998, 'Comal', 'Puce', '5UXFE83558L125957', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', 'Silhouette', 1995, 'Al Kittah', 'Violet', '1NXBE4EE6AZ502054', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', '745', 2004, 'Potrerillos', 'Red', '1N6AD0CU3EN495275', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'M5', 2001, 'Matou', 'Goldenrod', 'WAUCFAFR0CA185878', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'CL-Class', 2009, 'Mazār-e Sharīf', 'Goldenrod', 'WAUFGBFC6EN702589', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Sonata', 2000, 'Kołbaskowo', 'Red', '5TDBCRFH1FS007126', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'FX', 2008, 'El Chol', 'Violet', '5GAKVCKD4DJ284035', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Aspire', 1994, 'Xiaosong', null, '4T1BF1FK8EU612674', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Focus', 2001, 'Augusta', 'Fuscia', '1N6AA0CC2AN327184', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', '2500', 1998, 'Dolní Čermná', 'Violet', 'WAULFAFR7BA973345', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Saab', '900', 1992, 'Tangwang', 'Red', 'WBAAV33461F397165', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'MX-3', 1992, 'Jatisari', 'Puce', 'KNAGM4AD5E5605621', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Civic', 1985, 'Robertsfors', 'Mauv', '1FTEX1C84AK103756', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Cabriolet', 1995, 'Prengtale', 'Crimson', 'JH4DB75511S361878', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Tahoe', 2005, 'Koungou', 'Turquoise', '2FMDK4AC4AB740543', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Range Rover', 2006, 'Yangzhong', 'Aquamarine', '2T1BURHE5EC278634', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'Vigor', 1992, 'Sydney', 'Orange', 'WAUBF78E37A172265', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chrysler', '300M', 1999, 'Ts’khinvali', 'Purple', '3C63DRNL8CG422467', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jaguar', 'S-Type', 2006, 'Ribeira Seca', 'Pink', 'SCBLE37G56C727101', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram 3500', 1994, 'Heqing', 'Teal', 'SCFFDAAE4CG146641', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', '300SE', 1992, 'Biruinţa', 'Aquamarine', '3C4PDCBB2FT670311', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Yukon Denali', 2000, 'Guéret', 'Violet', '1FTSW3B55AE379970', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'GTO', 1964, 'Cabeça Gorda', 'Orange', '1D7CW3GK5AS404217', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F150', 1998, 'Badaogu', 'Crimson', '1YVHZ8BA0A5361272', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'Z4', 2011, 'Hongchang', 'Goldenrod', 'JN1BJ0HR8FM032658', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'RL', 2004, 'Krynice', 'Blue', 'JN1AV7AP9FM287949', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Yukon XL 2500', 2013, 'Oslo', null, 'WBA3B1C58FK022147', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', '300SE', 1993, 'Pueblo Nuevo', 'Fuscia', '1GYFK26269R362393', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Tiburon', 2001, 'Priupskiy', 'Indigo', '1G6DV8EP0C0306694', true);
insert into cars (make, model, year, city, color, vin, broken) values ('MINI', 'Clubman', 2011, 'Krajan Kerjo', 'Red', 'WAUDN74FX8N874541', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'RDX', 2009, 'Kan’onjichō', 'Goldenrod', '1HGCP2E35CA360484', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Skylark', 1996, 'Ipameri', null, 'WBANU53589B672630', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'V8', 1994, 'Guantang', 'Teal', 'WAUXL68E94A755993', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Saab', '9-7X', 2008, 'Niyang', 'Violet', '19UYA42443A820217', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'NSX', 1997, 'Pyay', 'Yellow', 'WBA1M1C55FV105888', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Montana', 2006, 'Algueirão', 'Puce', '1GTG5AE30F1232965', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'GTI', 2001, 'Velikooktyabr’skiy', 'Indigo', 'WBAPN7C5XAA110577', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Explorer', 2003, 'Kermānshāh', 'Maroon', 'WAUKG78E66A111195', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lincoln', 'MKS', 2013, 'Liqi', 'Pink', '3VW517AT4FM518264', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Sable', 1996, 'Fonadhoo', 'Green', '1G6KD57Y09U206613', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Xtra', 1993, 'Jixiang', 'Turquoise', 'JN8AZ2KR3CT188893', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Precis', 1992, 'Liangdang Chengguanzhen', 'Red', 'SALVP2BG9FH718950', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'SRX', 2011, 'Gongming', 'Purple', 'WBAET37495N754187', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Eclipse', 1989, 'Santa Maria', 'Maroon', '1G6DT57V990580260', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Explorer', 2007, 'Purificación', 'Goldenrod', '1G4GD5G3XFF611428', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Trans Sport', 1992, 'Vanino', 'Yellow', '1VWAH7A39DC949773', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Accent', 1997, 'Taloy', 'Red', 'KNDPB3A24B7815306', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Beretta', 1995, 'Sundumbili', 'Maroon', 'WAUKG78EX6A288820', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Plymouth', 'Acclaim', 1992, 'Hilversum', 'Indigo', 'ZHWGU5BZ1CL691562', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Touareg', 2011, 'Vila Nova', 'Orange', 'ZHWGU6AU7CL097036', false);
insert into cars (make, model, year, city, color, vin, broken) values ('MINI', 'Clubman', 2011, 'Xiadian', 'Khaki', '2G4WD532551668280', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Cabriolet', 1999, 'Fria', 'Fuscia', 'SCBBP9ZA9DC003717', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'RX', 2007, 'Sambirejo', null, 'SCFFDABE7BG569114', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'SL-Class', 1989, 'Sindi', 'Crimson', 'WBANV13589B182971', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Porsche', 'Boxster', 2009, 'Gocoton', 'Violet', '1N6AF0KY3EN492682', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Merkur', 'XR4Ti', 1985, 'Taguisa', null, '2C3CDYCJ0DH121136', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', '4Runner', 2011, 'Checacupe', 'Teal', 'JN8AZ2ND5F9200656', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Tracker', 1999, 'Chełm', 'Crimson', '3D73M3CL7AG375122', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'IS', 2008, 'Lingcheng', 'Maroon', 'WAUGL68E25A498385', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'S-Class', 2005, 'Berthierville', 'Crimson', '1GYEC63828R435489', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Viper', 2006, 'Winduraja', null, 'KMHHT6KDXEU681843', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Solara', 2000, 'Guapimirim', 'Goldenrod', '3D7TT2CTXBG946228', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Impala', 2000, 'Arsenal', 'Teal', '1G4HF57968U975752', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Freestar', 2003, 'Liangkou', null, 'WAUGFAFR1BA558409', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'SL-Class', 2008, 'Al Mughayyir', 'Fuscia', 'WAUD2AFD6DN551406', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jaguar', 'S-Type', 2002, 'Mutatá', 'Pink', '1G6AB5SX4F0897907', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Forester', 2010, 'Matinha', 'Crimson', '1GKS1CKJ1FR211990', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'E-Series', 1985, 'Fukayachō', 'Aquamarine', '3D4PH5FV7AT925115', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', 'Bravada', 1998, 'Patambuco', null, 'KMHHT6KJ4FU608801', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Dakota Club', 1995, 'Zhangcaizhuang', 'Pink', 'KL4CJCSB6FB308677', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jensen', 'Interceptor', 1966, 'Lélouma', 'Green', '1N6AD0CW9FN111860', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lincoln', 'Continental Mark VII', 1987, 'Ligang', 'Goldenrod', 'SCBCU7ZA9AC588909', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Saab', '900', 1996, 'Seixo', 'Blue', '1GYFK668X8R260699', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F150', 2004, 'Örebro', 'Maroon', '5N1BA0NE8FN780640', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Tracker', 2001, 'Gangshangji', null, 'SCFFDAAM2DG525128', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'B2500', 2001, 'Takanabe', null, 'WAUMGAFL9BA980178', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lotus', 'Esprit', 1996, 'Bweyogerere', 'Puce', 'WAURVAFDXBN322513', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'Escalade ESV', 2009, 'Nevyts’ke', 'Pink', '5FNRL5H23CB145220', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Range Rover', 2009, 'Daga', 'Teal', '5FPYK1F27CB623415', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Econoline E150', 1998, 'Krasnorechenskiy', 'Purple', '1GYS3GEF1BR572712', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Corvette', 2006, 'Vetluzhskiy', 'Orange', '19UUA76678A000443', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 2500', 1996, 'Salaberry-de-Valleyfield', 'Puce', 'JH4CU2F69EC257736', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Prix', 1981, 'Ananindeua', 'Mauv', '1GYFK63858R682948', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Azera', 2010, 'Muyudian', 'Puce', '3VWML7AJ0BM762671', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Tiguan', 2010, 'Jiantiao', 'Turquoise', '19VDE1F54EE411419', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Mirage', 2000, 'Ulyanovsk', 'Green', '5N1AN0NWXEN911493', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Avalanche 1500', 2006, 'New York City', 'Crimson', '5GAKRAED5CJ120053', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Country', 1967, 'Lishan', 'Khaki', '2G61V5S87F9928086', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F250', 1996, 'Biskamzha', 'Purple', 'WAUAFAFL2CN312223', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'SC', 1995, 'Baykonyr', null, 'WA1AV94L09D457809', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Lucerne', 2008, 'Shirochanka', 'Crimson', '2D4RN7DGXBR610122', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Sable', 2000, 'Panenjoan', null, 'JN8AZ2KR1ET468850', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Ridgeline', 2012, 'Río Pico', 'Crimson', 'WAUFFAFL4DA385544', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', 'Aurora', 1995, 'Shimo-furano', 'Yellow', 'WAUVVAFR4AA893429', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'E350', 2010, 'Qārah', 'Aquamarine', '2C3CCAJG7DH982010', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Galant', 2006, 'Lochovice', 'Red', '3C3CFFDR1DT621817', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Vanagon', 1984, 'Kertosari', 'Aquamarine', '1GD01ZCG6BF797053', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'RAV4', 2007, 'Xinqiao', 'Orange', 'ML32A3HJ3EH580411', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Am', 1989, 'Vřesina', 'Turquoise', '3C4PDCBB9FT444556', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram Van 3500', 2002, 'Mrganush', null, 'WAUWFAFH6DN122895', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'Escalade ESV', 2007, 'Lansing', 'Teal', 'SALGS2DFXDA888767', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'M3', 2006, 'Lajas', 'Yellow', '1G6AB5RA0E0116381', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Prix', 2007, 'Zaragoza', 'Goldenrod', 'KMHCM3AC9BU962008', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chrysler', 'LHS', 1997, 'Pointe-Noire', 'Crimson', '2G4WE537851087056', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Grand Caravan', 1999, 'Pedra Azul', 'Violet', '2D4RN7DG2BR275597', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F350', 2012, 'Xiguantun Muguzu Manzuxiang', 'Crimson', 'JN8AE2KPXF9903695', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F250', 1992, 'Kawangu Satu', 'Indigo', 'WA1EY74L29D006880', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', '3 Series', 2002, 'Vřesina', 'Khaki', '19VDE1F30DE622971', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'XG300', 2001, 'New Plymouth', 'Goldenrod', 'SCFHDDAJ3AA559576', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lamborghini', 'Diablo', 1996, 'Solntsevo', null, 'KMHCT4AE4FU343252', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Grand Cherokee', 2001, 'Hongqiao', 'Yellow', '1FTEW1CW0AK498598', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Millenia', 2001, 'Goodlands', 'Mauv', '1B3CB1HA9BD858557', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Peugeot', '207', 2006, 'Karipidita', 'Fuscia', '1G6YV36A785710424', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 2500', 1998, 'Huizhou', 'Teal', 'WAUBH74F58N626261', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Sentra', 1991, 'Chuoyuan', 'Purple', '1G6DC67A190617840', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'SLK55 AMG', 2009, 'Paya Dapur', 'Mauv', '3GYFNDE39CS705991', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'MX-5', 1993, 'Jiangkou', 'Fuscia', 'WAUMGAFL5CA437640', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Jeep', 'Grand Cherokee', 2004, 'Magisterial', 'Khaki', 'JTDKTUD3XDD437658', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'S5', 2011, 'Liangwa', 'Mauv', '1G6DK5E36D0161067', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Rolls-Royce', 'Phantom', 2005, 'Kaffrine', 'Green', 'WDDEJ7EB3EA190275', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'S5', 2008, 'Araci', null, '2C3CK6CT3AH726436', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'Alpina B7', 2008, 'Pargas', 'Purple', 'WBA3V5C57EJ530709', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', 'Achieva', 1993, 'Manabo', 'Violet', '3VWJX7AJ6AM827500', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram Wagon B350', 1994, 'Tizgane', 'Indigo', 'JH4DC53063C715786', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Milan', 2006, 'Pawing', 'Violet', '3C6JD6DT4CG239171', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', '5000S', 1985, 'Viškovci', 'Fuscia', 'WAUEF98E18A570651', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', '90', 1995, 'Brasília', 'Blue', '3VW4A7ATXCM732733', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Mazdaspeed 3', 2007, 'Shangchewan', 'Yellow', '2HNYD2H4XDH460028', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Golf', 1996, 'Ekerö', 'Mauv', 'WAULT68E22A433353', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Riviera', 1989, 'Santa María del Real', 'Indigo', '4T1BK3DB1AU807780', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Outlander', 2011, 'Katsuta', 'Fuscia', 'KNDPB3A26D7836953', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'QX', 2001, 'Kuroishi', 'Indigo', '5NPDH4AE7DH088971', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'V40', 2001, 'Bašaid', 'Fuscia', '1G6DA8EY1B0211144', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'G-Series G30', 1993, 'Bungkulan', 'Khaki', 'JTHDU1EFXB5131997', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maybach', 'Landaulet', 2012, 'Gachancipá', 'Maroon', '1FMJU1J56AE266192', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Camry', 1995, 'Svay Rieng', 'Pink', 'KNAFX6A80F5118703', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Camry Hybrid', 2009, 'Liyang', 'Green', 'WAUMK98K89N150554', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Sonoma Club Coupe', 1997, 'Edinburgh', 'Pink', '4T3BK3BB2FU650729', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Silverado 1500', 2001, 'Nīkshahr', 'Purple', '1G6DE1E31E0909614', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Firebird Trans Am', 1986, 'Tyukalinsk', 'Indigo', '1FMJK1JT7FE279559', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Terraza', 2007, 'Nicoya', 'Yellow', 'WA1BV74L57D909596', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Tiburon', 2004, 'Maketu', 'Puce', '1GTC5LF95C8762817', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercury', 'Cougar', 1969, 'Cardona', 'Pink', 'WP0AA2A99DS143291', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'S4', 2007, 'Thala', 'Pink', '3C63DRNL2CG245608', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Range Rover', 2012, 'Kajatian', 'Puce', '4USBT33524L635938', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', '6 Series', 2008, 'Halinów', 'Violet', '5N1AA0ND3FN882186', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'GLK-Class', 2010, 'Surovikino', null, '1GD322CG2EF190069', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Ranger', 1991, 'Kai', 'Goldenrod', 'WA1YL64B15N760984', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Corolla', 2008, 'Meïganga', 'Red', '1G6AJ5SX6E0519170', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'X5', 2011, 'Jiangcun', 'Aquamarine', '1G6DJ8ED1B0376060', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Enclave', 2009, 'Ōtawara', 'Blue', '4T1BF3EK7BU760615', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lotus', 'Esprit', 1990, 'Béziers', 'Orange', 'WAUDF98E37A666467', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Mighty Max', 1986, 'Ikeja', 'Puce', 'WBAWC73528E525848', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Holden', 'VS Commodore', 1995, 'Kurchaloy', 'Turquoise', '1N4AB7AP1EN261348', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Sunfire', 2001, 'León', 'Violet', 'WAUVT54B94N118009', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Saab', '9-2X', 2005, 'Jiaoyuan', 'Pink', 'WVWGU7AN8AE911574', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'Sprinter 2500', 2012, 'Kasli', 'Green', '1N6AD0CW7FN640689', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Altima', 2002, 'Leran Wetan', 'Teal', 'WVGFG9BP1BD370353', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Malibu', 1999, 'Quevedo', 'Turquoise', '3C63DRNL5CG409417', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'CR-V', 2002, 'Jiushe', 'Red', '4A31K2DF0BE463719', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'Escalade', 2010, 'Batawa', 'Turquoise', '3C63DRNLXCG486266', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F350', 2011, 'Shanghe', 'Blue', '3GYFK66N03G422693', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Avalon', 1999, 'Nhà Bè', 'Goldenrod', 'KMHHT6KD0CU184653', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Econoline E150', 1998, 'Hexi', null, '1GD21ZCG6DZ240833', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Flex', 2012, 'Madan', 'Pink', 'YV1672MK6A2662887', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Sierra 3500', 2006, 'Rosignol', 'Purple', '2T1BU4EE8DC738195', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Diamante', 1996, 'Apodi', 'Pink', '1GT02ZCG5EF270210', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'GS', 2009, 'Yeniköy', 'Fuscia', '2FMPK3J98FB244079', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'S-Class', 1989, 'Santa Maria da Vitória', null, 'JN8AZ2KRXAT201247', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Acura', 'RL', 1999, 'Liushun', 'Fuscia', 'JM1CW2BL5C0986256', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'S90', 1997, 'Bajawa', 'Puce', '1GKS1HE09ER199408', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Prizm', 2002, 'Água de Pau', 'Maroon', 'WBA3C3C56FK409028', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Freelander', 2002, 'Ronggui', 'Pink', '3D73Y4EL4BG288934', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', '3500', 1999, 'Iława', 'Puce', '4T1BD1EB5EU027378', true);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'X3', 2007, 'Raleigh', 'Blue', '1FTSX2B56AE989013', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Isuzu', 'Amigo', 2000, 'Valle Grande', 'Mauv', 'WBALM7C52AE771899', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Prix', 1989, 'Zhushan', 'Goldenrod', 'JM1BL1K5XB1550317', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Saturn', 'S-Series', 1998, 'Yanzhou', 'Orange', '5N1AA0ND8FN025197', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chrysler', 'LeBaron', 1992, 'Omaha', 'Indigo', 'YV4902DZ6C2488565', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'ES', 2005, 'San Diego', 'Blue', 'WBAVM5C56FV390092', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Tacoma Xtra', 1997, 'Hanušovice', 'Purple', 'JTDKN3DP9D3648928', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Eagle', 'Talon', 1997, 'Bendan', 'Red', '3D7TT2CT3BG291216', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Mazda3', 2009, 'Río Grande', 'Maroon', '3VWML7AJ7CM892254', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'LS', 2009, 'Pithári', 'Crimson', 'WA1YD64B12N491426', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Hyundai', 'Veloster', 2013, 'Bulembu', null, '1FTFW1E81AF523245', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Am', 1988, 'Jõhvi', 'Green', 'KNALN4D76E5518862', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Corolla', 2005, 'Litvínov', 'Aquamarine', 'WBA3V5C59F5191056', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Firebird', 1988, 'West Island', 'Puce', '2C3CDXFG1FH185649', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Prizm', 2000, 'Courtaboeuf', 'Violet', '1FTEX1E88AF936269', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'A4', 2007, 'Miaotou', 'Crimson', 'JH4CU2E81EC615480', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'G-Class', 2008, 'Shanmu', 'Pink', 'WAUYGAFC4DN836387', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Tracker', 1998, 'Quixadá', 'Teal', '2D4RN3D16AR258790', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Expedition', 2004, 'Granja', 'Violet', 'WBAKF5C59CE304931', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Lexus', 'ES', 2004, 'Pinheiro', 'Indigo', '1ZVBP8AM7D5908651', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Camaro', 2000, 'Delgerhaan', 'Orange', 'WAUFFAFL8AA167070', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Grand Prix', 1997, 'Kontiolahti', null, '2T1BU4EE4DC429050', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Discovery', 2000, 'Chapimarca', 'Goldenrod', '2C3CK3CV9AH516391', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Camry Solara', 2006, 'Krajan Caluk', 'Red', 'SCBCP7ZA6AC654257', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', '90', 1991, 'Is', 'Fuscia', '2T1BURHE3EC075032', false);
insert into cars (make, model, year, city, color, vin, broken) values ('BMW', 'Z3', 2001, 'Oslo', 'Mauv', '3N1CE2CP5FL409533', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ferrari', 'F430', 2007, 'Kakuda', 'Indigo', 'WAUKH74FX8N178874', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Solstice', 2008, 'Ḩarf al Musaytirah', 'Green', 'JN8AE2KP7E9659955', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Element', 2005, 'Molagavita', null, 'WBSWL93568P195854', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'S5', 2008, 'Yangjiaqiao', null, 'WBABD33494J967653', false);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Acadia', 2011, 'Sirājganj', 'Aquamarine', 'WBALX3C59CD745454', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', 'Pathfinder', 2005, 'High Prairie', 'Teal', 'WAUGN94F99N608289', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Sonoma', 1994, 'Hénin-Beaumont', 'Indigo', 'SCFHDDAJ4CA914273', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Volkswagen', 'Cabriolet', 2001, 'Paphos', 'Khaki', '1FTSW2B50AE788243', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Camry Hybrid', 2007, 'Nuoxizhi', 'Puce', '1G6AB5RX7E0299864', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Subaru', 'Outback', 2010, 'Shiroi', 'Fuscia', '5TFBW5F18DX685365', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Camry Solara', 2008, 'Grebenskaya', 'Teal', 'ZHWGU6AU6CL109810', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'G-Series G30', 1993, 'Malvas', 'Teal', 'WBAEN33484E976475', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'CTS', 2006, 'Santa Cruz', 'Pink', 'WBSKG9C55DJ091825', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', '600SEL', 1992, 'Gora', 'Red', '1G6AY5S35F0887639', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Caprice Classic', 1996, 'Paradela', 'Khaki', 'JM1NC2LF4C0805478', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Cadillac', 'Escalade ESV', 2012, 'Kopang Satu', 'Maroon', 'YV1622FSXC2958087', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Caravan', 1998, 'Kobilje', null, 'JTDKN3DU0F0554091', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'MPV', 1995, 'Stockholm', 'Green', '2HNYD18261H571907', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Toyota', 'Prius', 2009, 'Mikrókampos', 'Red', 'WAUAFAFL6AN473610', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Land Rover', 'Discovery', 2003, 'Gahe', 'Mauv', 'WAUVC68E72A805116', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Excel', 1988, 'Caçador', 'Crimson', '1G6DG5EG2A0535805', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', '98', 1996, 'Leipzig', 'Turquoise', '5N1BA0NC4FN119380', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Fiesta', 2013, 'Beixiang', null, 'WBA4B3C55FG404669', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Saturn', 'S-Series', 1992, 'Chagoda', 'Teal', '3LNHL2GC5CR492627', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'LeSabre', 1987, 'Noyakert', null, '2C3CDYAG1DH068180', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Porsche', 'Cayman', 2009, 'Niba', 'Purple', '3D7TP2CT1BG947546', true);
insert into cars (make, model, year, city, color, vin, broken) values ('GMC', 'Yukon XL 2500', 2012, 'Katsuyama', 'Orange', 'JA4AS2AW5BU633872', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Studebaker', 'Avanti', 1961, 'Bitobe', 'Maroon', '1GD11ZCGXBF106031', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Econoline E350', 1997, 'Waru', null, '2HNYD18655H480846', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Taurus', 1995, 'Jintun', 'Green', 'WAUCFAFR1EA244505', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Honda', 'Insight', 2004, 'Mehrābpur', null, '19XFB2E23CE908822', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'Crown Victoria', 1992, 'Preston', null, 'WVWAP7AN3EE062246', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Dodge', 'Ram Van B250', 1994, 'Xiyuan', null, 'WA1AV94L49D114100', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Audi', 'S4', 2008, 'Orimattila', 'Maroon', '2C4JRGAG2DR323069', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mazda', 'Tribute', 2010, 'Bergen', 'Turquoise', 'WA1LGBFE8ED852971', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Nissan', '350Z', 2008, 'Hanamaki', 'Khaki', '3VWKX7AJ9BM128349', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Volvo', 'XC90', 2010, 'Ivanteyevka', 'Green', 'W04GN5ECXB1911069', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Chevrolet', 'Express 2500', 2003, 'Naga', 'Red', '1GD02ZCGXEF616716', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'E-Series', 2008, 'Hongkou', 'Crimson', 'WBAPM5C59BA557703', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Buick', 'Century', 2005, 'Raciąż', 'Yellow', '1G4HF5EM2AU855699', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Maserati', 'Quattroporte', 1986, 'Sibulan', 'Purple', '1G6AS5S30E0765996', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Oldsmobile', 'Cutlass Cruiser', 1993, 'Lengkongjaya', 'Blue', '1G6DU57V190328127', true);
insert into cars (make, model, year, city, color, vin, broken) values ('Infiniti', 'QX', 1999, 'Verkhniye Kigi', 'Blue', '1C4SDJCT7DC560689', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Pontiac', 'Montana', 2001, 'Wilkowice', 'Crimson', 'WAUAT48H63K434457', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Ford', 'F350', 2006, 'Los Fresnos', 'Green', 'WUARL48HX8K408475', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', 'CLS-Class', 2009, 'Thuận Nam', 'Fuscia', '3D73M3CLXAG465851', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mitsubishi', 'Lancer Evolution', 2002, 'Perechyn', 'Fuscia', 'WAULD54B83N686321', false);
insert into cars (make, model, year, city, color, vin, broken) values ('Mercedes-Benz', '500SL', 1992, 'West Palm Beach', 'Fuscia', 'SCFEBBCF2BG224183', true);
