name: NodeJS


on:
  push:
    branches: [ main, lecture* ]
  pull_request:
    branches:
      - main
      - lecture*

jobs:
  build and test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.16.1
#        - 16.x
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd lecture_13/video-hosting
        npm install
        npm run build

    - name: Test
      run: |
        cd lecture_13/video-hosting
        npm run test:cov
